### ISSUE TITLE
USB audio card wrong address in itop output

### ISSUE THREAD

**Issue by hifi25nl** [kargig/itop#3]
I have an usb audio card on this address:
cat /proc/asound/card1/usbbus
004/002
but...
itop -a is giving only this:
uhci_hcd:usb2 ( 21):               0               0               0
ehci_hcd:usb8 ( 23):               3               6               9
I think ehci_hcd:usb8 or uhci_hcd:usb2 should be instead uhci_hcd:usb4, am I right?

**Comment by kargig** [comment]
itop parses /proc/interrupts. Can you see your device there ?

**Comment by hifi25nl** [comment]
This is the interesting part of /proc/interrupts
 23:     414181      81892   IO-APIC  23-fasteoi   uhci_hcd:usb4, ehci_hcd:usb8

My card is at  uhci_hcd:usb4, but if I start itop and play an audio file only ehci_hcd:usb8 is increasing values.

uhci_hcd:usb2 ( 21):               0               0               0
ehci_hcd:usb8 ( 23):             200               0             200

and usb4 is completely missing in the output  (but is there in proc/interrupts).
My guess is that for some reason itop is showing only a part of devices associated with an irq, but really is detecting them (see 200 in the line before)

**Comment by kargig** [comment]
I created a new branch that displays a second device sharing an IRQ. Please test it and tell me whether it works for you now. 
https://github.com/kargig/itop/tree/2devices

If it doesn't, please post the full output of your /proc/interrupts

**Comment by kargig** [comment]
does it work for you ? if so, please respond so I can merge the branches.

**Comment by hifi25nl** [comment]
Sorry for the late answer but I didn't receive last post.
Now it seems working.

I have made a PKGBUILD for archlinux here:
https://aur.archlinux.org/packages/itop-git/
I will update it as soon as you merge the branches.

**Comment by kargig** [comment]
I've pushed a commit into "2devices" branch that adds support for more than 2 devices sharing the same IRQ. Can you test that as well please ?

**Comment by hifi25nl** [comment]
I think it is working.
The problem I see is that uhci_hcd, ehci_hcd etc. sometime are shown sometime not

Proc/interrupts  --> 
 16:        850       3723   IO-APIC  16-fasteoi   uhci_hcd:usb1, firewire_ohci
 17:          0          0   IO-APIC  17-fasteoi   mmc0
 18:      85688     248461   IO-APIC  18-fasteoi   uhci_hcd:usb6, ehci_hcd:usb7, i801_smbus
 19:      23575      44484   IO-APIC  19-fasteoi   mmc1, uhci_hcd:usb3, uhci_hcd:usb5, ata_piix
 21:         17         18   IO-APIC  21-fasteoi   uhci_hcd:usb2
 23:     290490     359467   IO-APIC  23-fasteoi   uhci_hcd:usb4, ehci_hcd:usb8
 27:     486741     586175   PCI-MSI-edge      enp0s25
 28:          9          8   PCI-MSI-edge      mei_me
 29:        524       1205   PCI-MSI-edge      snd_hda_intel
 30:     374397    1256521   PCI-MSI-edge      nvidia

itop --> 

firewire_ohci,usb1 ( 16):         0         0         0
                    mmc0 ( 17):         0         0         0
    i801_smbus,usb7,usb6 ( 18):         9        57        66
      ata_piix,usb5,usb3 ( 19):         0         0         0
           uhci_hcd:usb2 ( 21):         0         0         0
      ehci_hcd:usb8,usb4 ( 23):        13        15        28
                 enp0s25 ( 27):        80        94       174
                  mei_me ( 28):         0         0         0
           snd_hda_intel ( 29):         0         0         0
                  nvidia ( 30):        21        53        74

**Comment by kargig** [comment]
in order to minimize the space needed I removed '*hci_hcd' string from the device name when multiple devices were using the same IRQ. That would be OK if all the devices were using uhci or ehci, but your output shows that you have both a uhci and an ehci device sharing the same IRQ.

which naming scheme do you prefer:
 * uhci_hcd:usb6, ehci_hcd:usb7, i801_smbus
 * uhci:usb6,ehci:usb7,i801_smbus
 * usb6,usb7,i801_smbus

I think I prefer the last one.

**Comment by hifi25nl** [comment]
I think the second one: this  is complete but more compact then the first

**Comment by kargig** [comment]
okay...second option it is. Test again please

**Comment by hifi25nl** [comment]
It seems fine.
